name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Build
        run: npm run build

      - id: GCP Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'

      - name: Build Docker Image
        run : docker run -e PORT=8080 -p 8080:8080 ahmadmkacher/notely:latest

      - name: Push image to GC-AR
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-507611/notely-ar-repo/notely:latest .
